[build]
builder = "DOCKERFILE"
dockerfilePath = "dockerfile"

[deploy]
startCommand = "python start_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
